"""Run hierarchical SPE with development-only MIL member selection.

This command performs inference only.  It never retrains base MIL models and
never uses independent-test labels to select states, folds, architectures, or
weights.  Expected inputs are five ``every_epoch`` training folds per
architecture, each containing ``spe_checkpoint_selection.json`` generated by
``utils.spe_model_utils``.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import re
import sys
from pathlib import Path, PurePosixPath
from typing import Any

import numpy as np
import pandas as pd
import torch
import yaml
from torch.utils.data import DataLoader


REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from ensemble.spe import (
    architecture_disagreement,
    fit_architecture_weights,
    patient_equal_sample_weights,
    residual_similarity_matrix,
    select_architectures,
)
from utils.model_utils import get_model_from_yaml
from utils.wsi_utils import WSI_Dataset
from utils.yaml_utils import read_yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Stable states -> folds -> diversity-aware architectures SPE"
    )
    parser.add_argument(
        "--spe-config",
        type=Path,
        default=Path("configs/Diagnosis/SPE/hierarchical_spe.yaml"),
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Recompute cached checkpoint predictions.",
    )
    parser.add_argument(
        "--preflight",
        action="store_true",
        help="Validate configs, datasets, runs and selected checkpoints without inference.",
    )
    return parser.parse_args()


def resolve_path(value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else REPO_ROOT / path


def atomic_csv(frame: pd.DataFrame, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_suffix(output_path.suffix + ".tmp")
    frame.to_csv(temporary, index=False)
    temporary.replace(output_path)


def atomic_json(payload: dict[str, Any], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_suffix(output_path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(output_path)


def fold_number(path: Path) -> int:
    match = re.search(r"_(\d+)fold\.csv$", path.name, flags=re.IGNORECASE)
    if match is None:
        raise ValueError(f"Cannot parse fold number from: {path}")
    return int(match.group(1))


def fold_csvs(root: Path) -> dict[int, Path]:
    if not root.is_dir():
        raise FileNotFoundError(f"Dataset directory not found: {root}")
    paths: dict[int, Path] = {}
    for path in root.glob("*.csv"):
        if re.search(r"_(\d+)fold\.csv$", path.name, flags=re.IGNORECASE):
            paths[fold_number(path)] = path
    if sorted(paths) != [1, 2, 3, 4, 5]:
        raise ValueError(f"Expected folds 1..5 in {root}, found {sorted(paths)}")
    return paths


def selected_checkpoints(fold_dir: Path) -> list[Path]:
    selection_path = fold_dir / "spe_checkpoint_selection.json"
    if not selection_path.is_file():
        raise FileNotFoundError(
            f"Missing {selection_path}. SPE requires a run trained with "
            "General.checkpoint.save_mode=every_epoch; best+last alone cannot "
            "reconstruct the paper's stable-state interval."
        )
    selection = json.loads(selection_path.read_text(encoding="utf-8"))
    records = selection.get("selected_checkpoints", [])
    if not 1 <= len(records) <= 5:
        raise ValueError(
            f"{selection_path} must select 1..5 checkpoints, found {len(records)}."
        )
    checkpoints = [fold_dir / str(record["checkpoint"]) for record in records]
    missing = [path for path in checkpoints if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"Selected checkpoint files are missing: {missing}")
    return checkpoints


def complete_spe_run(run_dir: Path) -> bool:
    try:
        for fold in range(1, 6):
            selected_checkpoints(run_dir / f"fold_{fold}")
        return True
    except (FileNotFoundError, ValueError, KeyError, json.JSONDecodeError):
        return False


def discover_run(config: Any, configured_run_dir: str | None) -> Path:
    if configured_run_dir:
        run_dir = resolve_path(configured_run_dir)
        if not complete_spe_run(run_dir):
            raise FileNotFoundError(f"Not a complete five-fold SPE run: {run_dir}")
        return run_dir
    model_root = (
        resolve_path(config.Logs.log_root_dir)
        / str(config.Dataset.DATASET_NAME)
        / str(config.General.MODEL_NAME)
    )
    candidates = sorted(
        [path for path in model_root.glob(f"seed_{config.General.seed}_*") if path.is_dir()],
        key=lambda path: (path.stat().st_mtime, path.name),
        reverse=True,
    )
    for candidate in candidates:
        if complete_spe_run(candidate):
            return candidate
    raise FileNotFoundError(
        f"No complete SPE training run under {model_root}. Re-run this architecture "
        "with every_epoch checkpoint saving enabled."
    )


def patient_id_from_slide(slide_id: str) -> str:
    """Match the patient key used by the patient-level Diagnosis split."""
    return str(slide_id).split(".", 1)[0]


def split_metadata(dataset_csv: Path, split: str) -> pd.DataFrame:
    source = pd.read_csv(dataset_csv)
    path_column = f"{split}_slide_path"
    label_column = f"{split}_label"
    required = {path_column, label_column}
    if not required.issubset(source.columns):
        raise ValueError(f"{dataset_csv} is missing {sorted(required - set(source.columns))}")
    subset = source.loc[source[path_column].notna(), [path_column, label_column]].copy()
    subset.columns = ["slide_path", "label"]
    subset["slide_id"] = subset["slide_path"].map(
        lambda value: PurePosixPath(str(value).replace("\\", "/")).stem
    )
    subset["patient_id"] = subset["slide_id"].map(patient_id_from_slide)
    subset["label"] = subset["label"].astype(int)
    type_column = f"{split}_type"
    if type_column in source.columns:
        subset["type"] = source.loc[source[path_column].notna(), type_column].astype("string")
    else:
        subset["type"] = pd.Series(pd.NA, index=subset.index, dtype="string")
    subset = subset[["slide_id", "patient_id", "type", "label", "slide_path"]].reset_index(drop=True)
    if subset["slide_id"].duplicated().any():
        duplicates = subset.loc[subset["slide_id"].duplicated(False), "slide_id"].tolist()
        raise ValueError(f"Duplicate slide IDs in {dataset_csv} [{split}]: {duplicates[:5]}")
    return subset


def load_state_dict(checkpoint: Path):
    try:
        return torch.load(checkpoint, map_location="cpu", weights_only=True)
    except TypeError:
        return torch.load(checkpoint, map_location="cpu")


def positive_probability(output: Any, num_classes: int) -> torch.Tensor:
    if isinstance(output, dict):
        if "logits" not in output:
            raise TypeError("MIL output dictionary does not contain 'logits'.")
        logits = output["logits"]
    elif torch.is_tensor(output):
        logits = output
    elif isinstance(output, (tuple, list)) and output and torch.is_tensor(output[0]):
        logits = output[0]
    else:
        raise TypeError(f"Unsupported MIL model output: {type(output)!r}")
    logits = logits.reshape(-1, num_classes)[0]
    if num_classes != 2:
        raise ValueError("The paper's SPE implementation currently expects binary logits.")
    return torch.softmax(logits, dim=0)[1]


def infer_checkpoint(
    config: Any,
    dataset_csv: Path,
    split: str,
    checkpoint: Path,
    device: torch.device,
    num_workers: int,
    preload: bool,
) -> pd.DataFrame:
    metadata = split_metadata(dataset_csv, split)
    dataset = WSI_Dataset(str(dataset_csv), split, preload=preload)
    loader = DataLoader(
        dataset,
        batch_size=1,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=device.type == "cuda",
    )
    model = get_model_from_yaml(config)
    model.load_state_dict(load_state_dict(checkpoint), strict=True)
    model = model.to(device).eval()

    probabilities: list[float] = []
    observed_ids: list[str] = []
    observed_labels: list[int] = []
    with torch.inference_mode():
        for features, labels, slide_ids in loader:
            output = model(features.to(device, non_blocking=True).float())
            probabilities.append(
                float(positive_probability(output, int(config.General.num_classes)).cpu())
            )
            observed_ids.append(str(slide_ids[0]))
            observed_labels.append(int(labels.item()))

    if observed_ids != metadata["slide_id"].tolist():
        raise ValueError(f"Dataset order/IDs changed during inference: {dataset_csv} [{split}]")
    if observed_labels != metadata["label"].tolist():
        raise ValueError(f"Dataset labels changed during inference: {dataset_csv} [{split}]")
    result = metadata.drop(columns="slide_path").copy()
    result["prob_1"] = probabilities
    result["prob_0"] = 1.0 - result["prob_1"]
    result["checkpoint"] = checkpoint.name

    del model, loader, dataset
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return result


def validate_cached_state(frame: pd.DataFrame, metadata: pd.DataFrame, source: Path) -> pd.DataFrame:
    required = {"slide_id", "patient_id", "type", "label", "prob_1", "prob_0", "checkpoint"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Cached prediction {source} is missing {sorted(missing)}")
    if frame["slide_id"].astype(str).tolist() != metadata["slide_id"].astype(str).tolist():
        raise ValueError(f"Cached prediction IDs do not match {source}")
    if not np.allclose(frame["prob_0"] + frame["prob_1"], 1.0, atol=1e-6):
        raise ValueError(f"Invalid cached probabilities: {source}")
    return frame


def trajectory_predictions(state_frames: list[pd.DataFrame]) -> pd.DataFrame:
    if not state_frames:
        raise ValueError("A trajectory requires at least one state prediction.")
    metadata_columns = ["slide_id", "patient_id", "type", "label"]
    base = state_frames[0][metadata_columns].copy()
    probabilities = []
    for index, frame in enumerate(state_frames):
        pd.testing.assert_frame_equal(
            base.reset_index(drop=True),
            frame[metadata_columns].reset_index(drop=True),
            check_dtype=False,
        )
        probabilities.append(frame["prob_1"].to_numpy(dtype=np.float64))
    matrix = np.column_stack(probabilities)
    base["prob_1"] = matrix.mean(axis=1)
    base["prob_0"] = 1.0 - base["prob_1"]
    base["state_variance"] = matrix.var(axis=1, ddof=0)
    base["state_std"] = np.sqrt(base["state_variance"])
    base["state_count"] = matrix.shape[1]
    return base


def merge_architecture_oof(oof_by_architecture: dict[str, pd.DataFrame]) -> pd.DataFrame:
    names = list(oof_by_architecture)
    first = oof_by_architecture[names[0]]
    merged = first[["slide_id", "patient_id", "type", "label", "fold"]].copy()
    for name in names:
        frame = oof_by_architecture[name]
        columns = ["slide_id", "patient_id", "label", "fold", "prob_1"]
        renamed = frame[columns].rename(columns={"prob_1": f"prob_{name}"})
        merged = merged.merge(
            renamed,
            on=["slide_id", "patient_id", "label", "fold"],
            how="inner",
            validate="one_to_one",
        )
    expected = len(first)
    if len(merged) != expected or any(len(frame) != expected for frame in oof_by_architecture.values()):
        raise ValueError("Architectures do not cover the same OOF development slides.")
    return merged.sort_values(["fold", "slide_id"]).reset_index(drop=True)


def architecture_test_prediction(fold_frames: list[pd.DataFrame]) -> pd.DataFrame:
    if len(fold_frames) != 5:
        raise ValueError(f"Expected five fold trajectories, found {len(fold_frames)}")
    metadata_columns = ["slide_id", "patient_id", "type", "label"]
    base = fold_frames[0][metadata_columns].copy()
    fold_probabilities = []
    state_variances = []
    for frame in fold_frames:
        pd.testing.assert_frame_equal(
            base.reset_index(drop=True),
            frame[metadata_columns].reset_index(drop=True),
            check_dtype=False,
        )
        fold_probabilities.append(frame["prob_1"].to_numpy(dtype=np.float64))
        state_variances.append(frame["state_variance"].to_numpy(dtype=np.float64))
    fold_matrix = np.column_stack(fold_probabilities)
    base["prob_1"] = fold_matrix.mean(axis=1)
    base["prob_0"] = 1.0 - base["prob_1"]
    base["fold_variance"] = fold_matrix.var(axis=1, ddof=0)
    base["fold_std"] = np.sqrt(base["fold_variance"])
    base["state_variance"] = np.column_stack(state_variances).mean(axis=1)
    base["state_std"] = np.sqrt(base["state_variance"])
    return base


def run_architecture(
    architecture: dict[str, Any],
    development_folds: dict[int, Path],
    test_folds: dict[int, Path],
    work_root: Path,
    device: torch.device,
    num_workers: int,
    preload: bool,
    overwrite: bool,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    name = str(architecture["name"])
    config_path = resolve_path(architecture["config"])
    config = read_yaml(str(config_path))
    if str(config.General.MODEL_NAME) != name:
        raise ValueError(
            f"Architecture name {name} does not match {config_path}: {config.General.MODEL_NAME}"
        )
    run_dir = discover_run(config, architecture.get("run_dir"))
    architecture_root = work_root / name / run_dir.name
    fold_oof: list[pd.DataFrame] = []
    fold_test: list[pd.DataFrame] = []
    checkpoint_manifest: dict[str, list[str]] = {}

    for fold in range(1, 6):
        checkpoints = selected_checkpoints(run_dir / f"fold_{fold}")
        checkpoint_manifest[str(fold)] = [str(path) for path in checkpoints]
        outputs: dict[str, pd.DataFrame] = {}
        for split, dataset_csv in (("val", development_folds[fold]), ("test", test_folds[fold])):
            metadata = split_metadata(dataset_csv, split).drop(columns="slide_path")
            state_frames: list[pd.DataFrame] = []
            for checkpoint in checkpoints:
                state_path = (
                    architecture_root
                    / f"fold_{fold}"
                    / split
                    / f"{checkpoint.stem}.csv"
                )
                if state_path.exists() and not overwrite:
                    state = pd.read_csv(
                        state_path,
                        dtype={"slide_id": "string", "patient_id": "string", "type": "string"},
                    )
                    state = validate_cached_state(state, metadata, state_path)
                else:
                    print(f"[{name}] fold={fold} split={split} checkpoint={checkpoint.name}")
                    state = infer_checkpoint(
                        config,
                        dataset_csv,
                        split,
                        checkpoint,
                        device,
                        num_workers,
                        preload,
                    )
                    atomic_csv(state, state_path)
                state_frames.append(state)
            trajectory = trajectory_predictions(state_frames)
            trajectory["architecture"] = name
            trajectory["fold"] = fold
            trajectory_path = architecture_root / f"fold_{fold}" / split / "trajectory.csv"
            atomic_csv(trajectory, trajectory_path)
            outputs[split] = trajectory
        fold_oof.append(outputs["val"])
        fold_test.append(outputs["test"])

    architecture_oof = pd.concat(fold_oof, ignore_index=True)
    if architecture_oof["slide_id"].duplicated().any():
        raise ValueError(f"{name} OOF contains duplicate slide IDs.")
    architecture_test = architecture_test_prediction(fold_test)
    architecture_test["architecture"] = name
    atomic_csv(architecture_oof, architecture_root / "oof_predictions.csv")
    atomic_csv(architecture_test, architecture_root / "test_predictions.csv")
    return architecture_oof, architecture_test, {
        "config": str(config_path),
        "training_run": str(run_dir),
        "selected_checkpoints": checkpoint_manifest,
    }


def main() -> None:
    cli = parse_args()
    config_path = resolve_path(cli.spe_config)
    settings = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    experiment = settings["experiment"]
    architectures = settings["architectures"]
    names = [str(item["name"]) for item in architectures]
    if len(names) < 2 or len(set(names)) != len(names):
        raise ValueError("SPE requires at least two unique candidate MIL architectures.")

    development_folds = fold_csvs(resolve_path(experiment["development_dataset_root"]))
    test_folds = fold_csvs(resolve_path(experiment["independent_test_dataset_root"]))
    output_root = resolve_path(experiment["output_root"]) / str(experiment["name"])
    work_root = output_root / "member_predictions"
    threshold = float(experiment.get("classification_threshold", 0.5))
    if not 0.0 < threshold < 1.0:
        raise ValueError("classification_threshold must lie strictly between 0 and 1.")

    if cli.preflight:
        for architecture in architectures:
            name = str(architecture["name"])
            architecture_config = read_yaml(str(resolve_path(architecture["config"])))
            if str(architecture_config.General.MODEL_NAME) != name:
                raise ValueError(
                    f"Architecture name {name} does not match configured MODEL_NAME."
                )
            run_dir = discover_run(architecture_config, architecture.get("run_dir"))
            counts = [
                len(selected_checkpoints(run_dir / f"fold_{fold}"))
                for fold in range(1, 6)
            ]
            print(f"PASS {name}: run={run_dir} selected_states_per_fold={counts}")
        print("SPE preflight complete; no inference was performed.")
        return

    device = torch.device(str(experiment.get("device", "cuda:0")))
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is not available.")

    oof_by_architecture: dict[str, pd.DataFrame] = {}
    test_by_architecture: dict[str, pd.DataFrame] = {}
    run_manifest: dict[str, Any] = {}
    for architecture in architectures:
        name = str(architecture["name"])
        oof, test, metadata = run_architecture(
            architecture=architecture,
            development_folds=development_folds,
            test_folds=test_folds,
            work_root=work_root,
            device=device,
            num_workers=int(experiment.get("num_workers", 0)),
            preload=bool(experiment.get("preload", False)),
            overwrite=cli.overwrite,
        )
        oof_by_architecture[name] = oof
        test_by_architecture[name] = test
        run_manifest[name] = metadata

    oof = merge_architecture_oof(oof_by_architecture)
    probability_columns = [f"prob_{name}" for name in names]
    probability_matrix = oof[probability_columns].to_numpy(dtype=np.float64)
    weighting = settings.get("weighting", {})
    selection_settings = settings.get("selection", {})
    selection_enabled = bool(selection_settings.get("enabled", True))
    if selection_enabled:
        configured_max_members = selection_settings.get(
            "max_members", min(6, len(names))
        )
        selection = select_architectures(
            probability_matrix,
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            fold_ids=oof["fold"].to_numpy(),
            architecture_names=names,
            diversity_lambda=float(weighting.get("diversity_lambda", 0.05)),
            min_members=int(selection_settings.get("min_members", 2)),
            max_members=(
                None
                if configured_max_members is None
                else int(configured_max_members)
            ),
            min_cv_improvement=float(selection_settings.get("min_cv_improvement", 1e-3)),
            require_better_than_null=bool(
                selection_settings.get("require_better_than_null", True)
            ),
            max_individual_log_loss_gap=selection_settings.get(
                "max_individual_log_loss_gap", 0.10
            ),
            max_iterations=int(weighting.get("max_iterations", 5000)),
            tolerance=float(weighting.get("tolerance", 1e-10)),
        )
        selected_names = list(selection.selected_names)
        selection_manifest = selection.as_dict()
        eligible_names = set(selection.eligible_names)
        selection_steps = {step["added"]: step for step in selection.steps}
    else:
        selected_names = names.copy()
        selection_manifest = {
            "enabled": False,
            "candidate_names": names,
            "selected_names": names,
        }
        eligible_names = set(names)
        selection_steps = {}
    print(f"SPE selected {len(selected_names)}/{len(names)} architectures: {selected_names}")
    selected_indices = [names.index(name) for name in selected_names]
    selected_probability_matrix = probability_matrix[:, selected_indices]
    fit, _ = fit_architecture_weights(
        selected_probability_matrix,
        labels=oof["label"].to_numpy(),
        patient_ids=oof["patient_id"].astype(str).to_numpy(),
        architecture_names=selected_names,
        diversity_lambda=float(weighting.get("diversity_lambda", 0.05)),
        max_iterations=int(weighting.get("max_iterations", 5000)),
        tolerance=float(weighting.get("tolerance", 1e-10)),
    )
    selected_weights = np.asarray(fit.weights, dtype=np.float64)
    architecture_weights = np.zeros(len(names), dtype=np.float64)
    architecture_weights[selected_indices] = selected_weights
    oof["spe_prob_1"] = selected_probability_matrix @ selected_weights
    oof["spe_prediction"] = (oof["spe_prob_1"] >= threshold).astype(int)
    oof["architecture_disagreement"] = architecture_disagreement(
        selected_probability_matrix, selected_weights
    )
    atomic_csv(oof, output_root / "oof_architecture_predictions.csv")

    all_similarity = residual_similarity_matrix(
        probability_matrix,
        oof["label"].to_numpy(),
        patient_equal_sample_weights(oof["patient_id"].astype(str).to_numpy()),
    )
    similarity_frame = pd.DataFrame(all_similarity, index=names, columns=names)
    similarity_frame.index.name = "architecture"
    atomic_csv(similarity_frame.reset_index(), output_root / "residual_similarity.csv")

    weight_rows = []
    for index, name in enumerate(names):
        architecture_probability = probability_matrix[:, index]
        clipped = np.clip(architecture_probability, 1e-7, 1 - 1e-7)
        patient_weights = patient_equal_sample_weights(
            oof["patient_id"].astype(str).to_numpy()
        )
        log_loss = -np.sum(
            patient_weights
            * (oof["label"] * np.log(clipped) + (1 - oof["label"]) * np.log(1 - clipped))
        )
        weight_rows.append(
            {
                "architecture": name,
                "eligible": name in eligible_names,
                "selected": name in selected_names,
                "selection_step": selection_steps.get(name, {}).get("step"),
                "selection_cv_log_loss": selection_steps.get(name, {}).get(
                    "cross_validated_log_loss"
                ),
                "selection_improvement": selection_steps.get(name, {}).get(
                    "improvement"
                ),
                "weight": architecture_weights[index],
                "patient_equal_oof_log_loss": float(log_loss),
                "mean_residual_similarity_to_others": float(
                    np.delete(all_similarity[index], index).mean()
                ),
            }
        )
    atomic_csv(pd.DataFrame(weight_rows), output_root / "architecture_weights.csv")

    test_base = test_by_architecture[names[0]][
        ["slide_id", "patient_id", "type", "label"]
    ].copy()
    test_probability_columns = []
    state_variance_columns = []
    fold_variance_columns = []
    for name in names:
        frame = test_by_architecture[name]
        pd.testing.assert_frame_equal(
            test_base.reset_index(drop=True),
            frame[["slide_id", "patient_id", "type", "label"]].reset_index(drop=True),
            check_dtype=False,
        )
        probability_column = f"prob_{name}"
        state_column = f"state_variance_{name}"
        fold_column = f"fold_variance_{name}"
        test_base[probability_column] = frame["prob_1"].to_numpy()
        test_base[state_column] = frame["state_variance"].to_numpy()
        test_base[fold_column] = frame["fold_variance"].to_numpy()
        test_probability_columns.append(probability_column)
        state_variance_columns.append(state_column)
        fold_variance_columns.append(fold_column)
    atomic_csv(test_base, output_root / "architecture_test_predictions.csv")

    test_matrix = test_base[test_probability_columns].to_numpy(dtype=np.float64)[
        :, selected_indices
    ]
    state_variances = test_base[state_variance_columns].to_numpy(dtype=np.float64)[
        :, selected_indices
    ]
    fold_variances = test_base[fold_variance_columns].to_numpy(dtype=np.float64)[
        :, selected_indices
    ]
    final = test_base[["slide_id", "patient_id", "type", "label"]].copy()
    final["prob_1"] = test_matrix @ selected_weights
    final["prob_0"] = 1.0 - final["prob_1"]
    final["prediction"] = (final["prob_1"] >= threshold).astype(int)
    final["state_disagreement"] = np.sqrt(state_variances @ selected_weights)
    final["fold_disagreement"] = np.sqrt(fold_variances @ selected_weights)
    final["architecture_disagreement"] = architecture_disagreement(
        test_matrix, selected_weights
    )
    final["equal_weight_prob_1"] = test_matrix.mean(axis=1)
    final["equal_weight_prediction"] = (
        final["equal_weight_prob_1"] >= threshold
    ).astype(int)
    final["majority_vote_prediction"] = (
        (test_matrix >= threshold).sum(axis=1) >= (len(selected_names) // 2 + 1)
    ).astype(int)
    atomic_csv(final, output_root / "spe_predictions.csv")

    config_hash = hashlib.sha256(config_path.read_bytes()).hexdigest()
    manifest = {
        "schema_version": 2,
        "method": "stability-prioritized-hierarchical-ensemble",
        "hierarchy": [
            "stable_checkpoint_states",
            "five_folds",
            "development_only_architecture_selection",
            "selected_architecture_weighting",
        ],
        "spe_config": str(config_path),
        "spe_config_sha256": config_hash,
        "development_only_weight_fit": True,
        "development_only_architecture_selection": selection_enabled,
        "independent_test_labels_used_for_fit": False,
        "classification_threshold": threshold,
        "weight_fit": fit.as_dict(),
        "architecture_selection": selection_manifest,
        "architectures": run_manifest,
        "outputs": {
            "oof": str(output_root / "oof_architecture_predictions.csv"),
            "weights": str(output_root / "architecture_weights.csv"),
            "residual_similarity": str(output_root / "residual_similarity.csv"),
            "architecture_test": str(output_root / "architecture_test_predictions.csv"),
            "spe_predictions": str(output_root / "spe_predictions.csv"),
        },
    }
    atomic_json(manifest, output_root / "manifest.json")
    print(f"SPE complete: {output_root / 'spe_predictions.csv'}")


if __name__ == "__main__":
    main()
