"""Run the paper-defined hierarchical SPE from saved MIL trajectories.

This command performs inference only.  It never retrains base MIL models and
never uses independent-test labels to select states, folds, architectures, or
weights.  Expected inputs are five ``every_epoch`` training folds per
architecture, each containing ``spe_checkpoint_selection.json`` generated by
``utils.spe_model_utils``.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import gc
import hashlib
import json
import multiprocessing
import re
import sys
from pathlib import Path, PurePosixPath
from typing import Any

import numpy as np
import pandas as pd
import torch
import yaml
from torch.utils.data import DataLoader


REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from ensemble.spe import (
    architecture_disagreement,
    class_patient_equal_sample_weights,
    fit_architecture_weights,
    fit_constrained_linear_stacking,
    patient_equal_sample_weights,
    residual_similarity_matrix,
    select_architectures,
    select_architectures_for_balanced_accuracy,
    select_diversity_veto,
    select_sensitivity_constrained_subset,
    select_top1_anchor_with_fallback,
)
from ensemble.ra_spe import fit_ra_spe, predict_ra_spe, ra_spe_checkpoint
from utils.model_utils import get_model_from_yaml
from utils.wsi_utils import WSI_Dataset
from utils.yaml_utils import read_yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Stable states -> folds -> diversity-aware architectures SPE"
    )
    parser.add_argument(
        "--spe-config",
        type=Path,
        default=Path("configs/Diagnosis/SPE/hierarchical_spe.yaml"),
    )
    parser.add_argument(
        "--devices",
        type=str,
        default=None,
        help=(
            "Comma-separated inference devices, e.g. cuda:0,cuda:1. "
            "Overrides experiment.devices/device."
        ),
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Recompute cached checkpoint predictions.",
    )
    parser.add_argument(
        "--preflight",
        action="store_true",
        help="Validate configs, datasets, runs and selected checkpoints without inference.",
    )
    parser.add_argument(
        "--refit-from",
        type=Path,
        default=None,
        help=(
            "Reuse oof_architecture_predictions.csv and "
            "architecture_test_predictions.csv from an existing SPE output "
            "directory; skips all model inference."
        ),
    )
    parser.add_argument(
        "--test-dataset-csv",
        type=Path,
        default=None,
        help=(
            "Standalone CSV with test_slide_path/test_label columns. The same "
            "locked cohort is evaluated by all five folds and overrides "
            "experiment.independent_test_dataset_root."
        ),
    )
    parser.add_argument(
        "--output-name",
        type=str,
        default=None,
        help="Override experiment.name, useful for named locked runs.",
    )
    parser.add_argument(
        "--cohort-name",
        choices=("Internal", "External"),
        default=None,
        help=(
            "Output cohort directory below experiment.output_root. Defaults to "
            "Internal, or External when --test-dataset-csv is supplied."
        ),
    )
    return parser.parse_args()


def resolve_path(value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else REPO_ROOT / path


def resolve_cohort_name(
    test_dataset_csv: Path | None,
    configured_name: str | None,
) -> str:
    """Return the stable top-level output group for a locked test cohort."""
    if configured_name is not None:
        if configured_name not in {"Internal", "External"}:
            raise ValueError("cohort name must be 'Internal' or 'External'.")
        return configured_name
    return "External" if test_dataset_csv is not None else "Internal"


def atomic_csv(frame: pd.DataFrame, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_suffix(output_path.suffix + ".tmp")
    frame.to_csv(temporary, index=False)
    temporary.replace(output_path)


def atomic_json(payload: dict[str, Any], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_suffix(output_path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(output_path)


def fold_number(path: Path) -> int:
    match = re.search(r"_(\d+)fold\.csv$", path.name, flags=re.IGNORECASE)
    if match is None:
        raise ValueError(f"Cannot parse fold number from: {path}")
    return int(match.group(1))


def fold_csvs(root: Path) -> dict[int, Path]:
    if not root.is_dir():
        raise FileNotFoundError(f"Dataset directory not found: {root}")
    paths: dict[int, Path] = {}
    for path in root.glob("*.csv"):
        if re.search(r"_(\d+)fold\.csv$", path.name, flags=re.IGNORECASE):
            paths[fold_number(path)] = path
    if sorted(paths) != [1, 2, 3, 4, 5]:
        raise ValueError(f"Expected folds 1..5 in {root}, found {sorted(paths)}")
    return paths


def _evenly_spaced_records(
    records: list[dict[str, Any]], count: int
) -> list[dict[str, Any]]:
    if len(records) <= count:
        return records
    if count == 1:
        return [max(records, key=lambda record: int(record["epoch"]))]
    indices = [
        round(index * (len(records) - 1) / (count - 1))
        for index in range(count)
    ]
    return [records[index] for index in indices]


def selected_checkpoints(
    fold_dir: Path,
    policy: dict[str, Any] | None = None,
) -> list[Path]:
    policy = policy or {}
    strategy = str(policy.get("strategy", "precomputed_stability"))
    if strategy == "best_state":
        checkpoints = sorted(fold_dir.glob("Best_EPOCH_*.pth"))
        if len(checkpoints) != 1:
            raise FileNotFoundError(
                f"Expected exactly one Best_EPOCH checkpoint in {fold_dir}, "
                f"found {len(checkpoints)}."
            )
    elif strategy == "high_performance_band":
        manifest_path = fold_dir / "checkpoint_manifest.json"
        if not manifest_path.is_file():
            raise FileNotFoundError(f"Missing checkpoint trajectory: {manifest_path}")
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        metric = str(policy.get("metric", "bacc"))
        tolerance = float(policy.get("metric_tolerance", 0.005))
        max_checkpoints = int(policy.get("max_checkpoints", 5))
        if tolerance < 0 or not 1 <= max_checkpoints <= 5:
            raise ValueError(
                "checkpoint_selection requires metric_tolerance >= 0 and "
                "max_checkpoints in 1..5."
            )
        records = [
            record
            for record in manifest.get("epochs", [])
            if record.get("checkpoint")
            and isinstance(record.get("val_metrics", {}).get(metric), (int, float))
        ]
        if not records:
            raise ValueError(
                f"No checkpoints in {manifest_path} contain val_metrics.{metric}."
            )
        best_metric = max(float(record["val_metrics"][metric]) for record in records)
        eligible = sorted(
            (
                record
                for record in records
                if float(record["val_metrics"][metric]) >= best_metric - tolerance
            ),
            key=lambda record: int(record["epoch"]),
        )
        chosen = _evenly_spaced_records(eligible, max_checkpoints)
        checkpoints = [fold_dir / str(record["checkpoint"]) for record in chosen]
    elif strategy == "precomputed_stability":
        selection_path = fold_dir / "spe_checkpoint_selection.json"
        if not selection_path.is_file():
            raise FileNotFoundError(
                f"Missing {selection_path}. SPE requires a run trained with "
                "General.checkpoint.save_mode=every_epoch; best+last alone cannot "
                "reconstruct the paper's stable-state interval."
            )
        selection = json.loads(selection_path.read_text(encoding="utf-8"))
        records = selection.get("selected_checkpoints", [])
        if not 1 <= len(records) <= 5:
            raise ValueError(
                f"{selection_path} must select 1..5 checkpoints, found {len(records)}."
            )
        checkpoints = [fold_dir / str(record["checkpoint"]) for record in records]
    else:
        raise ValueError(f"Unknown checkpoint_selection.strategy={strategy!r}.")
    missing = [path for path in checkpoints if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"Selected checkpoint files are missing: {missing}")
    return checkpoints


def complete_spe_run(
    run_dir: Path, checkpoint_selection: dict[str, Any] | None = None
) -> bool:
    try:
        for fold in range(1, 6):
            selected_checkpoints(
                run_dir / f"fold_{fold}", checkpoint_selection
            )
        return True
    except (FileNotFoundError, ValueError, KeyError, json.JSONDecodeError):
        return False


def discover_run(
    config: Any,
    configured_run_dir: str | None,
    checkpoint_selection: dict[str, Any] | None = None,
) -> Path:
    if configured_run_dir:
        run_dir = resolve_path(configured_run_dir)
        if not complete_spe_run(run_dir, checkpoint_selection):
            raise FileNotFoundError(f"Not a complete five-fold SPE run: {run_dir}")
        return run_dir
    model_root = (
        resolve_path(config.Logs.log_root_dir)
        / str(config.Dataset.DATASET_NAME)
        / str(config.General.MODEL_NAME)
    )
    candidates = sorted(
        [path for path in model_root.glob(f"seed_{config.General.seed}_*") if path.is_dir()],
        key=lambda path: (path.stat().st_mtime, path.name),
        reverse=True,
    )
    for candidate in candidates:
        if complete_spe_run(candidate, checkpoint_selection):
            return candidate
    raise FileNotFoundError(
        f"No complete five-fold training run under {model_root} satisfies "
        f"checkpoint_selection={checkpoint_selection or {'strategy': 'precomputed_stability'}}."
    )


def patient_id_from_slide(slide_id: str) -> str:
    """Match the patient key used by the patient-level Diagnosis split."""
    value = str(slide_id)
    external_ynzl = re.fullmatch(r"(\d{4}-\d+)-\d+\.\d+", value)
    if external_ynzl is not None:
        return external_ynzl.group(1)
    if "." in value:
        return value.split(".", 1)[0]
    external_301 = re.fullmatch(
        r"(B\d+)-\d+(?:\(\d+\))?", value, flags=re.IGNORECASE
    )
    if external_301 is not None:
        return external_301.group(1)
    external_ynzl_x = re.fullmatch(r"(X\d{4}-\d+)-\d+", value, flags=re.IGNORECASE)
    if external_ynzl_x is not None:
        return external_ynzl_x.group(1)
    return value


def split_metadata(dataset_csv: Path, split: str) -> pd.DataFrame:
    source = pd.read_csv(dataset_csv)
    path_column = f"{split}_slide_path"
    label_column = f"{split}_label"
    required = {path_column, label_column}
    if not required.issubset(source.columns):
        raise ValueError(f"{dataset_csv} is missing {sorted(required - set(source.columns))}")
    subset = source.loc[source[path_column].notna(), [path_column, label_column]].copy()
    subset.columns = ["slide_path", "label"]
    subset["slide_id"] = subset["slide_path"].map(
        lambda value: PurePosixPath(str(value).replace("\\", "/")).stem
    )
    subset["patient_id"] = subset["slide_id"].map(patient_id_from_slide)
    subset["label"] = subset["label"].astype(int)
    type_column = f"{split}_type"
    if type_column in source.columns:
        subset["type"] = source.loc[source[path_column].notna(), type_column].astype("string")
    else:
        subset["type"] = pd.Series(pd.NA, index=subset.index, dtype="string")
    subset = subset[["slide_id", "patient_id", "type", "label", "slide_path"]].reset_index(drop=True)
    if subset["slide_id"].duplicated().any():
        duplicates = subset.loc[subset["slide_id"].duplicated(False), "slide_id"].tolist()
        raise ValueError(f"Duplicate slide IDs in {dataset_csv} [{split}]: {duplicates[:5]}")
    return subset


def load_state_dict(checkpoint: Path):
    try:
        return torch.load(checkpoint, map_location="cpu", weights_only=True)
    except TypeError:
        return torch.load(checkpoint, map_location="cpu")


def positive_probability(output: Any, num_classes: int) -> torch.Tensor:
    if isinstance(output, dict):
        if "logits" not in output:
            raise TypeError("MIL output dictionary does not contain 'logits'.")
        logits = output["logits"]
    elif torch.is_tensor(output):
        logits = output
    elif isinstance(output, (tuple, list)) and output and torch.is_tensor(output[0]):
        logits = output[0]
    else:
        raise TypeError(f"Unsupported MIL model output: {type(output)!r}")
    logits = logits.reshape(-1, num_classes)[0]
    if num_classes != 2:
        raise ValueError("The paper's SPE implementation currently expects binary logits.")
    return torch.softmax(logits, dim=0)[1]


def prepare_inference_model(
    config: Any,
    checkpoint_state: Any,
    device: torch.device,
) -> torch.nn.Module | tuple[torch.nn.Module, ...]:
    """Construct and load either a regular MIL model or the four-part DTFD model."""
    model = get_model_from_yaml(config)
    if str(config.General.MODEL_NAME) == "DTFD_MIL":
        component_names = ("classifier", "attention", "dimReduction", "attCls")
        if not isinstance(model, tuple) or len(model) != len(component_names):
            raise TypeError("DTFD_MIL factory must return four model components.")
        if not isinstance(checkpoint_state, dict):
            raise TypeError("DTFD_MIL checkpoint must be a dictionary of components.")
        missing = [name for name in component_names if name not in checkpoint_state]
        if missing:
            raise KeyError(f"DTFD_MIL checkpoint is missing components: {missing}")
        loaded_components = []
        for name, component in zip(component_names, model):
            component.load_state_dict(checkpoint_state[name], strict=True)
            loaded_components.append(component.to(device).eval())
        return tuple(loaded_components)

    if not isinstance(model, torch.nn.Module):
        raise TypeError(
            f"{config.General.MODEL_NAME} factory returned {type(model)!r}, "
            "expected torch.nn.Module."
        )
    model.load_state_dict(checkpoint_state, strict=True)
    return model.to(device).eval()


def dtfd_positive_probability(
    features: torch.Tensor,
    model_components: tuple[torch.nn.Module, ...],
    config: Any,
) -> torch.Tensor:
    """Reproduce the DTFD validation forward pass for one WSI bag."""
    classifier, attention, dim_reduction, attention_classifier = model_components
    num_groups = int(config.Model.num_Group)
    total_instance = int(config.Model.total_instance)
    if num_groups < 1 or total_instance < 1:
        raise ValueError("DTFD_MIL num_Group and total_instance must be positive.")
    instance_per_group = total_instance // num_groups
    pseudo_features = []
    for sub_features in torch.chunk(features.squeeze(0), num_groups, dim=0):
        mid_features = dim_reduction(sub_features)
        attention_weights = attention(mid_features).squeeze(0)
        attended_features = torch.einsum(
            "ns,n->ns", mid_features, attention_weights
        )
        attended_bag = attended_features.sum(dim=0, keepdim=True)

        classifier_weights = list(classifier.parameters())[-2]
        patch_logits = torch.einsum(
            "bgf,cf->bcg", attended_features.unsqueeze(0), classifier_weights
        ).squeeze(0).transpose(0, 1)
        patch_probabilities = torch.softmax(patch_logits, dim=1)
        sorted_indices = torch.argsort(
            patch_probabilities[:, -1], descending=True
        )
        top_indices = sorted_indices[:instance_per_group].long()
        bottom_indices = sorted_indices[-instance_per_group:].long()

        distill = str(config.Model.distill)
        if distill == "MaxMinS":
            chosen = torch.cat([top_indices, bottom_indices], dim=0)
            pseudo_features.append(mid_features.index_select(0, chosen))
        elif distill == "MaxS":
            pseudo_features.append(mid_features.index_select(0, top_indices))
        elif distill == "AFS":
            pseudo_features.append(attended_bag)
        else:
            raise ValueError(f"Unsupported DTFD_MIL distill mode: {distill}")

    if not pseudo_features or any(features.numel() == 0 for features in pseudo_features):
        raise ValueError(
            "DTFD_MIL produced an empty pseudo bag; ensure total_instance is at "
            "least num_Group for MaxMinS/MaxS distillation."
        )
    logits = attention_classifier(torch.cat(pseudo_features, dim=0))["logits"]
    return torch.softmax(logits.reshape(-1, int(config.General.num_classes))[0], dim=0)[1]


def infer_checkpoint(
    config: Any,
    dataset_csv: Path,
    split: str,
    checkpoint: Path,
    device: torch.device,
    num_workers: int,
    preload: bool,
) -> pd.DataFrame:
    metadata = split_metadata(dataset_csv, split)
    dataset = WSI_Dataset(str(dataset_csv), split, preload=preload)
    loader = DataLoader(
        dataset,
        batch_size=1,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=device.type == "cuda",
    )
    model = prepare_inference_model(config, load_state_dict(checkpoint), device)

    probabilities: list[float] = []
    observed_ids: list[str] = []
    observed_labels: list[int] = []
    with torch.inference_mode():
        for features, labels, slide_ids in loader:
            features = features.to(device, non_blocking=True).float()
            if str(config.General.MODEL_NAME) == "DTFD_MIL":
                probability = dtfd_positive_probability(features, model, config)
            else:
                probability = positive_probability(
                    model(features), int(config.General.num_classes)
                )
            probabilities.append(float(probability.cpu()))
            observed_ids.append(str(slide_ids[0]))
            observed_labels.append(int(labels.item()))

    if observed_ids != metadata["slide_id"].tolist():
        raise ValueError(f"Dataset order/IDs changed during inference: {dataset_csv} [{split}]")
    if observed_labels != metadata["label"].tolist():
        raise ValueError(f"Dataset labels changed during inference: {dataset_csv} [{split}]")
    result = metadata.drop(columns="slide_path").copy()
    result["prob_1"] = probabilities
    result["prob_0"] = 1.0 - result["prob_1"]
    result["checkpoint"] = checkpoint.name

    del model, loader, dataset
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return result


def validate_cached_state(frame: pd.DataFrame, metadata: pd.DataFrame, source: Path) -> pd.DataFrame:
    required = {"slide_id", "patient_id", "type", "label", "prob_1", "prob_0", "checkpoint"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Cached prediction {source} is missing {sorted(missing)}")
    if frame["slide_id"].astype(str).tolist() != metadata["slide_id"].astype(str).tolist():
        raise ValueError(f"Cached prediction IDs do not match {source}")
    if not np.allclose(frame["prob_0"] + frame["prob_1"], 1.0, atol=1e-6):
        raise ValueError(f"Invalid cached probabilities: {source}")
    return frame


def trajectory_predictions(state_frames: list[pd.DataFrame]) -> pd.DataFrame:
    if not state_frames:
        raise ValueError("A trajectory requires at least one state prediction.")
    metadata_columns = ["slide_id", "patient_id", "type", "label"]
    base = state_frames[0][metadata_columns].copy()
    probabilities = []
    for index, frame in enumerate(state_frames):
        pd.testing.assert_frame_equal(
            base.reset_index(drop=True),
            frame[metadata_columns].reset_index(drop=True),
            check_dtype=False,
        )
        probabilities.append(frame["prob_1"].to_numpy(dtype=np.float64))
    matrix = np.column_stack(probabilities)
    base["prob_1"] = matrix.mean(axis=1)
    base["prob_0"] = 1.0 - base["prob_1"]
    base["state_variance"] = matrix.var(axis=1, ddof=0)
    base["state_std"] = np.sqrt(base["state_variance"])
    base["state_count"] = matrix.shape[1]
    return base


def merge_architecture_oof(
    oof_by_architecture: dict[str, pd.DataFrame],
    architecture_names: list[str],
) -> pd.DataFrame:
    names = list(architecture_names)
    if set(names) != set(oof_by_architecture):
        raise ValueError("architecture_names do not match the OOF prediction mapping.")
    first = oof_by_architecture[names[0]]
    merged = first[["slide_id", "patient_id", "type", "label", "fold"]].copy()
    for name in names:
        frame = oof_by_architecture[name]
        columns = ["slide_id", "patient_id", "label", "fold", "prob_1"]
        if "state_variance" in frame.columns:
            columns.append("state_variance")
        renamed = frame[columns].rename(
            columns={
                "prob_1": f"prob_{name}",
                "state_variance": f"state_variance_{name}",
            }
        )
        merged = merged.merge(
            renamed,
            on=["slide_id", "patient_id", "label", "fold"],
            how="inner",
            validate="one_to_one",
        )
    expected = len(first)
    if len(merged) != expected or any(len(frame) != expected for frame in oof_by_architecture.values()):
        raise ValueError("Architectures do not cover the same OOF development slides.")
    return merged.sort_values(["fold", "slide_id"]).reset_index(drop=True)


def recover_cached_oof_state_variances(
    oof: pd.DataFrame,
    refit_source: Path,
    architecture_names: list[str],
    run_manifest: dict[str, Any],
) -> pd.DataFrame:
    """Recover reliability features omitted by older merged OOF CSV schemas."""
    recovered = oof.copy()
    for name in architecture_names:
        destination = f"state_variance_{name}"
        if destination in recovered.columns:
            continue
        architecture_root = refit_source / "member_predictions" / name
        candidates = list(architecture_root.glob("*/oof_predictions.csv"))
        training_run = run_manifest.get(name, {}).get("training_run")
        if training_run:
            run_name = Path(str(training_run)).name
            candidates = [path for path in candidates if path.parent.name == run_name]
        if len(candidates) != 1:
            continue
        member = pd.read_csv(
            candidates[0],
            dtype={"slide_id": "string", "patient_id": "string"},
        )
        required = {"slide_id", "patient_id", "label", "fold", "state_variance"}
        if not required.issubset(member.columns):
            continue
        reliability = member[list(required)].rename(
            columns={"state_variance": destination}
        )
        recovered = recovered.merge(
            reliability,
            on=["slide_id", "patient_id", "label", "fold"],
            how="left",
            validate="one_to_one",
        )
        if recovered[destination].isna().any():
            raise ValueError(f"Could not align cached OOF state variance for {name}.")
    return recovered


def architecture_test_prediction(fold_frames: list[pd.DataFrame]) -> pd.DataFrame:
    if len(fold_frames) != 5:
        raise ValueError(f"Expected five fold trajectories, found {len(fold_frames)}")
    metadata_columns = ["slide_id", "patient_id", "type", "label"]
    base = fold_frames[0][metadata_columns].copy()
    fold_probabilities = []
    state_variances = []
    for frame in fold_frames:
        pd.testing.assert_frame_equal(
            base.reset_index(drop=True),
            frame[metadata_columns].reset_index(drop=True),
            check_dtype=False,
        )
        fold_probabilities.append(frame["prob_1"].to_numpy(dtype=np.float64))
        state_variances.append(frame["state_variance"].to_numpy(dtype=np.float64))
    fold_matrix = np.column_stack(fold_probabilities)
    base["prob_1"] = fold_matrix.mean(axis=1)
    base["prob_0"] = 1.0 - base["prob_1"]
    base["fold_variance"] = fold_matrix.var(axis=1, ddof=0)
    base["fold_std"] = np.sqrt(base["fold_variance"])
    base["state_variance"] = np.column_stack(state_variances).mean(axis=1)
    base["state_std"] = np.sqrt(base["state_variance"])
    return base


def merge_architecture_test_predictions(
    test_by_architecture: dict[str, pd.DataFrame],
    architecture_names: list[str],
) -> pd.DataFrame:
    """Merge test predictions while keeping metadata validation immutable."""
    if not architecture_names:
        raise ValueError("At least one test architecture is required.")
    metadata_columns = ["slide_id", "patient_id", "type", "label"]
    reference = test_by_architecture[architecture_names[0]][metadata_columns].copy()
    merged = reference.copy()
    for name in architecture_names:
        frame = test_by_architecture[name]
        pd.testing.assert_frame_equal(
            reference.reset_index(drop=True),
            frame[metadata_columns].reset_index(drop=True),
            check_dtype=False,
        )
        merged[f"prob_{name}"] = frame["prob_1"].to_numpy()
        merged[f"state_variance_{name}"] = frame["state_variance"].to_numpy()
        merged[f"fold_variance_{name}"] = frame["fold_variance"].to_numpy()
    return merged


def configured_devices(experiment: dict[str, Any], cli_devices: str | None) -> list[str]:
    """Resolve and validate the requested architecture-level worker devices."""
    if cli_devices is not None:
        devices = [value.strip() for value in cli_devices.split(",") if value.strip()]
    elif "devices" in experiment:
        configured = experiment["devices"]
        if not isinstance(configured, list):
            raise ValueError("experiment.devices must be a YAML list.")
        devices = [str(value).strip() for value in configured if str(value).strip()]
    else:
        devices = [str(experiment.get("device", "cuda:0"))]
    if not devices:
        raise ValueError("At least one inference device is required.")
    if len(set(devices)) != len(devices):
        raise ValueError("Inference devices must be unique; do not duplicate one GPU.")
    parsed = [torch.device(value) for value in devices]
    cuda_devices = [device for device in parsed if device.type == "cuda"]
    if cuda_devices and not torch.cuda.is_available():
        raise RuntimeError("CUDA inference devices were requested but CUDA is unavailable.")
    cuda_count = torch.cuda.device_count()
    for device in cuda_devices:
        index = 0 if device.index is None else device.index
        if index < 0 or index >= cuda_count:
            raise ValueError(
                f"Requested {device}, but only {cuda_count} CUDA device(s) are visible."
            )
    return devices


def run_architecture(
    architecture: dict[str, Any],
    development_folds: dict[int, Path],
    test_folds: dict[int, Path],
    work_root: Path,
    device: torch.device,
    num_workers: int,
    preload: bool,
    overwrite: bool,
    checkpoint_selection: dict[str, Any],
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    name = str(architecture["name"])
    config_path = resolve_path(architecture["config"])
    config = read_yaml(str(config_path))
    if str(config.General.MODEL_NAME) != name:
        raise ValueError(
            f"Architecture name {name} does not match {config_path}: {config.General.MODEL_NAME}"
        )
    run_dir = discover_run(
        config, architecture.get("run_dir"), checkpoint_selection
    )
    architecture_root = work_root / name / run_dir.name
    fold_oof: list[pd.DataFrame] = []
    fold_test: list[pd.DataFrame] = []
    checkpoint_manifest: dict[str, list[str]] = {}

    for fold in range(1, 6):
        checkpoints = selected_checkpoints(
            run_dir / f"fold_{fold}", checkpoint_selection
        )
        checkpoint_manifest[str(fold)] = [str(path) for path in checkpoints]
        outputs: dict[str, pd.DataFrame] = {}
        for split, dataset_csv in (("val", development_folds[fold]), ("test", test_folds[fold])):
            metadata = split_metadata(dataset_csv, split).drop(columns="slide_path")
            state_frames: list[pd.DataFrame] = []
            for checkpoint in checkpoints:
                state_path = (
                    architecture_root
                    / f"fold_{fold}"
                    / split
                    / f"{checkpoint.stem}.csv"
                )
                if state_path.exists() and not overwrite:
                    state = pd.read_csv(
                        state_path,
                        dtype={"slide_id": "string", "patient_id": "string", "type": "string"},
                    )
                    state = validate_cached_state(state, metadata, state_path)
                else:
                    print(f"[{name}] fold={fold} split={split} checkpoint={checkpoint.name}")
                    state = infer_checkpoint(
                        config,
                        dataset_csv,
                        split,
                        checkpoint,
                        device,
                        num_workers,
                        preload,
                    )
                    atomic_csv(state, state_path)
                state_frames.append(state)
            trajectory = trajectory_predictions(state_frames)
            trajectory["architecture"] = name
            trajectory["fold"] = fold
            trajectory_path = architecture_root / f"fold_{fold}" / split / "trajectory.csv"
            atomic_csv(trajectory, trajectory_path)
            outputs[split] = trajectory
        fold_oof.append(outputs["val"])
        fold_test.append(outputs["test"])

    architecture_oof = pd.concat(fold_oof, ignore_index=True)
    if architecture_oof["slide_id"].duplicated().any():
        raise ValueError(f"{name} OOF contains duplicate slide IDs.")
    architecture_test = architecture_test_prediction(fold_test)
    architecture_test["architecture"] = name
    atomic_csv(architecture_oof, architecture_root / "oof_predictions.csv")
    atomic_csv(architecture_test, architecture_root / "test_predictions.csv")
    return architecture_oof, architecture_test, {
        "config": str(config_path),
        "training_run": str(run_dir),
        "selected_checkpoints": checkpoint_manifest,
    }


def _run_architecture_shard(
    architectures: list[dict[str, Any]],
    development_folds: dict[int, Path],
    test_folds: dict[int, Path],
    work_root: Path,
    device_name: str,
    num_workers: int,
    preload: bool,
    overwrite: bool,
    checkpoint_selection: dict[str, Any],
) -> list[dict[str, Any]]:
    """Evaluate one architecture shard sequentially on one dedicated device."""
    device = torch.device(device_name)
    if device.type == "cuda":
        torch.cuda.set_device(device)
    completed: list[dict[str, Any]] = []
    for architecture in architectures:
        name = str(architecture["name"])
        print(f"[{device_name}] starting {name}", flush=True)
        _, _, metadata = run_architecture(
            architecture=architecture,
            development_folds=development_folds,
            test_folds=test_folds,
            work_root=work_root,
            device=device,
            num_workers=num_workers,
            preload=preload,
            overwrite=overwrite,
            checkpoint_selection=checkpoint_selection,
        )
        architecture_root = work_root / name / Path(metadata["training_run"]).name
        metadata["inference_device"] = device_name
        completed.append(
            {
                "name": name,
                "oof_path": str(architecture_root / "oof_predictions.csv"),
                "test_path": str(architecture_root / "test_predictions.csv"),
                "metadata": metadata,
            }
        )
        print(f"[{device_name}] completed {name}", flush=True)
    return completed


def evaluate_architectures(
    architectures: list[dict[str, Any]],
    development_folds: dict[int, Path],
    test_folds: dict[int, Path],
    work_root: Path,
    devices: list[str],
    num_workers: int,
    preload: bool,
    overwrite: bool,
    checkpoint_selection: dict[str, Any],
) -> list[dict[str, Any]]:
    """Run independent MIL architectures in one spawn process per GPU."""
    worker_count = min(len(devices), len(architectures))
    shards = [architectures[index::worker_count] for index in range(worker_count)]
    if worker_count == 1:
        return _run_architecture_shard(
            shards[0],
            development_folds,
            test_folds,
            work_root,
            devices[0],
            num_workers,
            preload,
            overwrite,
            checkpoint_selection,
        )

    print(
        f"Parallel SPE inference: {len(architectures)} architectures across "
        f"{worker_count} devices {devices[:worker_count]}",
        flush=True,
    )
    completed: list[dict[str, Any]] = []
    spawn_context = multiprocessing.get_context("spawn")
    with concurrent.futures.ProcessPoolExecutor(
        max_workers=worker_count,
        mp_context=spawn_context,
    ) as executor:
        futures = [
            executor.submit(
                _run_architecture_shard,
                shard,
                development_folds,
                test_folds,
                work_root,
                devices[index],
                num_workers,
                preload,
                overwrite,
                checkpoint_selection,
            )
            for index, shard in enumerate(shards)
        ]
        try:
            for future in concurrent.futures.as_completed(futures):
                completed.extend(future.result())
        except BaseException:
            for future in futures:
                future.cancel()
            raise
    return completed


def main() -> None:
    cli = parse_args()
    config_path = resolve_path(cli.spe_config)
    settings = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    experiment = settings["experiment"]
    architectures = settings["architectures"]
    checkpoint_selection = settings.get("checkpoint_selection", {})
    names = [str(item["name"]) for item in architectures]

    experiment_name = str(cli.output_name or experiment["name"])
    cohort_name = resolve_cohort_name(cli.test_dataset_csv, cli.cohort_name)
    output_root = (
        resolve_path(experiment["output_root"]) / cohort_name / experiment_name
    )
    work_root = output_root / "member_predictions"
    threshold = float(experiment.get("classification_threshold", 0.5))
    if not 0.0 < threshold < 1.0:
        raise ValueError("classification_threshold must lie strictly between 0 and 1.")

    if cli.preflight:
        fold_csvs(resolve_path(experiment["development_dataset_root"]))
        if cli.test_dataset_csv is None:
            fold_csvs(resolve_path(experiment["independent_test_dataset_root"]))
        else:
            standalone_test_csv = resolve_path(cli.test_dataset_csv)
            if not standalone_test_csv.is_file():
                raise FileNotFoundError(
                    f"Standalone test CSV not found: {standalone_test_csv}"
                )
            split_metadata(standalone_test_csv, "test")
        for architecture in architectures:
            name = str(architecture["name"])
            architecture_config = read_yaml(str(resolve_path(architecture["config"])))
            if str(architecture_config.General.MODEL_NAME) != name:
                raise ValueError(
                    f"Architecture name {name} does not match configured MODEL_NAME."
                )
            run_dir = discover_run(
                architecture_config,
                architecture.get("run_dir"),
                checkpoint_selection,
            )
            counts = [
                len(
                    selected_checkpoints(
                        run_dir / f"fold_{fold}", checkpoint_selection
                    )
                )
                for fold in range(1, 6)
            ]
            print(f"PASS {name}: run={run_dir} selected_states_per_fold={counts}")
        print("SPE preflight complete; no inference was performed.")
        return

    refit_source = None
    if cli.refit_from is not None:
        refit_source = resolve_path(cli.refit_from).resolve()
        oof_path = refit_source / "oof_architecture_predictions.csv"
        test_path = refit_source / "architecture_test_predictions.csv"
        if not oof_path.is_file() or not test_path.is_file():
            raise FileNotFoundError(
                "--refit-from must contain oof_architecture_predictions.csv "
                "and architecture_test_predictions.csv."
            )
        oof = pd.read_csv(
            oof_path,
            dtype={"slide_id": "string", "patient_id": "string", "type": "string"},
        )
        test_base = pd.read_csv(
            test_path,
            dtype={"slide_id": "string", "patient_id": "string", "type": "string"},
        )
        source_manifest_path = refit_source / "manifest.json"
        if source_manifest_path.is_file():
            source_manifest = json.loads(source_manifest_path.read_text(encoding="utf-8"))
            run_manifest = source_manifest.get("architectures", {})
            if (
                str(checkpoint_selection.get("strategy", "")) == "best_state"
                and source_manifest.get("checkpoint_selection") != checkpoint_selection
            ):
                raise ValueError(
                    "--refit-from does not use the requested best_state checkpoint "
                    "policy. Generate a Best-state prediction pool first."
                )
        else:
            run_manifest = {}
            if str(checkpoint_selection.get("strategy", "")) == "best_state":
                raise ValueError(
                    "A best_state --refit-from directory must contain manifest.json "
                    "so its checkpoint policy can be verified."
                )
        oof = recover_cached_oof_state_variances(
            oof, refit_source, names, run_manifest
        )
        devices: list[str] = []
        print(f"Refitting cached architecture predictions from {refit_source}")
    else:
        devices = configured_devices(experiment, cli.devices)
        development_folds = fold_csvs(
            resolve_path(experiment["development_dataset_root"])
        )
        if cli.test_dataset_csv is None:
            test_folds = fold_csvs(
                resolve_path(experiment["independent_test_dataset_root"])
            )
        else:
            standalone_test_csv = resolve_path(cli.test_dataset_csv)
            if not standalone_test_csv.is_file():
                raise FileNotFoundError(
                    f"Standalone test CSV not found: {standalone_test_csv}"
                )
            split_metadata(standalone_test_csv, "test")
            test_folds = {fold: standalone_test_csv for fold in range(1, 6)}
        oof_by_architecture: dict[str, pd.DataFrame] = {}
        test_by_architecture: dict[str, pd.DataFrame] = {}
        run_manifest: dict[str, Any] = {}
        completed = evaluate_architectures(
            architectures=architectures,
            development_folds=development_folds,
            test_folds=test_folds,
            work_root=work_root,
            devices=devices,
            num_workers=int(experiment.get("num_workers", 0)),
            preload=bool(experiment.get("preload", False)),
            overwrite=cli.overwrite,
            checkpoint_selection=checkpoint_selection,
        )
        for result in completed:
            name = str(result["name"])
            oof_by_architecture[name] = pd.read_csv(
                result["oof_path"],
                dtype={
                    "slide_id": "string",
                    "patient_id": "string",
                    "type": "string",
                },
            )
            test_by_architecture[name] = pd.read_csv(
                result["test_path"],
                dtype={
                    "slide_id": "string",
                    "patient_id": "string",
                    "type": "string",
                },
            )
            run_manifest[name] = result["metadata"]
        missing_results = set(names) - set(oof_by_architecture)
        if missing_results:
            raise RuntimeError(
                f"Architecture workers returned no result for {sorted(missing_results)}"
            )
        oof = merge_architecture_oof(oof_by_architecture, names)
        test_base = merge_architecture_test_predictions(test_by_architecture, names)

    probability_columns = [f"prob_{name}" for name in names]
    missing_oof_columns = set(probability_columns).difference(oof.columns)
    if missing_oof_columns:
        raise ValueError(
            f"OOF predictions are missing columns: {sorted(missing_oof_columns)}"
        )
    probability_matrix = oof[probability_columns].to_numpy(dtype=np.float64)
    if oof.groupby(oof["patient_id"].astype(str))["fold"].nunique().max() > 1:
        raise ValueError("A patient cannot occur in more than one OOF fold.")
    weighting = settings.get("weighting", {})
    aggregation = settings.get("aggregation", {})
    aggregation_strategy = str(aggregation.get("strategy", "weighted_mean"))
    decision_threshold = threshold
    selection_settings = settings.get("selection", {})
    selection = None
    reference_selection = None
    reference_fit = None
    selected_names = list(names)
    fit = None
    ra_fit = None
    ra_model = None
    ra_oof_weights = None
    linear_crossfit_weights = None
    linear_oof_weight_matrix = None
    anchor_guard = None
    anchor_guard_oof_probability = None
    anchor_guard_proposed_oof_probability = None
    if aggregation_strategy == "diversity_veto":
        selection = select_diversity_veto(
            probability_matrix,
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            architecture_names=names,
            classification_threshold=threshold,
            max_veto_bacc_gap=float(aggregation.get("max_veto_bacc_gap", 0.03)),
        )
        selected_names = list(selection.selected_names)
        print(
            "Selected diversity veto: "
            f"anchor={selection.anchor_name}, veto={selection.veto_name}"
        )
    elif aggregation_strategy == "sensitivity_constrained_subset":
        reference_settings = aggregation.get("reference_selection", {})
        reference_selection = select_architectures_for_balanced_accuracy(
            probability_matrix,
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            fold_ids=oof["fold"].to_numpy(),
            architecture_names=names,
            diversity_lambda=float(weighting.get("diversity_lambda", 0.05)),
            classification_threshold=threshold,
            min_members=int(reference_settings.get("min_members", 2)),
            max_members=int(reference_settings.get("max_members", 6)),
            min_cv_improvement=float(
                reference_settings.get("min_cv_improvement", 0.001)
            ),
            max_individual_bacc_gap=float(
                reference_settings.get("max_individual_bacc_gap", 0.10)
            ),
            max_iterations=int(weighting.get("max_iterations", 5000)),
            tolerance=float(weighting.get("tolerance", 1e-10)),
        )
        reference_names = list(reference_selection.selected_names)
        reference_indices = np.asarray(
            [names.index(name) for name in reference_names], dtype=int
        )
        reference_fit, _ = fit_architecture_weights(
            probability_matrix[:, reference_indices],
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            architecture_names=reference_names,
            diversity_lambda=float(weighting.get("diversity_lambda", 0.05)),
            max_iterations=int(weighting.get("max_iterations", 5000)),
            tolerance=float(weighting.get("tolerance", 1e-10)),
            class_balance=True,
        )
        reference_probability = probability_matrix[:, reference_indices] @ np.asarray(
            reference_fit.weights, dtype=np.float64
        )
        selection = select_sensitivity_constrained_subset(
            probability_matrix,
            labels=oof["label"].to_numpy(),
            architecture_names=names,
            reference_probabilities=reference_probability,
            reference_threshold=threshold,
            sensitivity_margin=float(aggregation.get("sensitivity_margin", 0.0)),
            min_members=int(aggregation.get("min_members", 1)),
            max_members=int(aggregation.get("max_members", 8)),
        )
        selected_names = list(selection.selected_names)
        decision_threshold = float(selection.classification_threshold)
        print(
            "Selected sensitivity-constrained subset: "
            f"members={selected_names}, threshold={decision_threshold:.8f}, "
            f"OOF sensitivity={selection.cross_validated_sensitivity:.6f}, "
            f"specificity={selection.cross_validated_specificity:.6f}"
        )
    elif aggregation_strategy not in {
        "weighted_mean",
        "constrained_linear_stacking",
        "ra_spe",
        "top1_anchor_fallback",
    }:
        raise ValueError(f"Unknown aggregation.strategy={aggregation_strategy!r}.")
    elif aggregation_strategy == "top1_anchor_fallback":
        anchor_guard, anchor_guard_oof_probability, anchor_guard_proposed_oof_probability = (
            select_top1_anchor_with_fallback(
                probability_matrix,
                labels=oof["label"].to_numpy(),
                patient_ids=oof["patient_id"].astype(str).to_numpy(),
                fold_ids=oof["fold"].to_numpy(),
                architecture_names=names,
                diversity_lambda=float(weighting.get("diversity_lambda", 0.02)),
                classification_threshold=threshold,
                anchor_min_weight=float(aggregation.get("anchor_min_weight", 0.70)),
                weight_grid_step=float(aggregation.get("weight_grid_step", 0.01)),
                min_members=int(selection_settings.get("min_members", 2)),
                max_members=int(selection_settings.get("max_members", 3)),
                min_cv_member_improvement=float(
                    selection_settings.get("min_cv_improvement", 0.0)
                ),
                max_individual_bacc_gap=(
                    None
                    if selection_settings.get("max_individual_bacc_gap") is None
                    else float(selection_settings["max_individual_bacc_gap"])
                ),
                min_oof_bacc_gain=float(
                    aggregation.get("min_oof_bacc_gain", 0.005)
                ),
                min_non_decreasing_folds=int(
                    aggregation.get("min_non_decreasing_folds", 4)
                ),
                fold_tolerance=float(aggregation.get("fold_tolerance", 0.0)),
            )
        )
        selection = anchor_guard
        selected_names = list(anchor_guard.deployed_names)
        mode = "Top1 fallback" if anchor_guard.fallback_triggered else "anchored ensemble"
        print(
            f"Top1-anchor guard: anchor={anchor_guard.anchor_name}, "
            f"proposal={list(anchor_guard.proposed_selected_names)}, "
            f"OOF gain={anchor_guard.balanced_accuracy_gain:.6f}, "
            f"non-decreasing folds={anchor_guard.non_decreasing_folds}/"
            f"{len(anchor_guard.fold_diagnostics)} -> {mode}"
        )
    elif aggregation_strategy == "weighted_mean" and bool(
        selection_settings.get("enabled", False)
    ):
        max_members_value = selection_settings.get("max_members")
        selection_objective = str(
            selection_settings.get("objective", "patient_equal_log_loss")
        )
        common_selection = {
            "probabilities": probability_matrix,
            "labels": oof["label"].to_numpy(),
            "patient_ids": oof["patient_id"].astype(str).to_numpy(),
            "fold_ids": oof["fold"].to_numpy(),
            "architecture_names": names,
            "diversity_lambda": float(weighting.get("diversity_lambda", 0.05)),
            "min_members": int(selection_settings.get("min_members", 1)),
            "max_members": (
                None if max_members_value is None else int(max_members_value)
            ),
            "min_cv_improvement": float(
                selection_settings.get("min_cv_improvement", 0.001)
            ),
            "max_iterations": int(weighting.get("max_iterations", 5000)),
            "tolerance": float(weighting.get("tolerance", 1e-10)),
        }
        if selection_objective == "balanced_accuracy":
            selection = select_architectures_for_balanced_accuracy(
                **common_selection,
                classification_threshold=threshold,
                max_individual_bacc_gap=(
                    None
                    if selection_settings.get("max_individual_bacc_gap") is None
                    else float(selection_settings["max_individual_bacc_gap"])
                ),
            )
        elif selection_objective == "patient_equal_log_loss":
            selection = select_architectures(
                **common_selection,
                require_better_than_null=bool(
                    selection_settings.get("require_better_than_null", True)
                ),
                max_individual_log_loss_gap=(
                    None
                    if selection_settings.get("max_individual_log_loss_gap") is None
                    else float(selection_settings["max_individual_log_loss_gap"])
                ),
            )
        else:
            raise ValueError(f"Unknown selection.objective={selection_objective!r}.")
        selected_names = list(selection.selected_names)
        print(f"Selected {len(selected_names)}/{len(names)} architectures: {selected_names}")

    selected_indices = np.asarray(
        [names.index(name) for name in selected_names], dtype=int
    )
    selected_probability_matrix = probability_matrix[:, selected_indices]
    architecture_weights = np.zeros(len(names), dtype=np.float64)
    if aggregation_strategy == "diversity_veto":
        architecture_weights[selected_indices] = 0.5
        oof["spe_prob_1"] = selected_probability_matrix.min(axis=1)
    elif aggregation_strategy == "sensitivity_constrained_subset":
        architecture_weights[selected_indices] = 1.0 / len(selected_indices)
        oof["spe_prob_1"] = selected_probability_matrix.mean(axis=1)
    elif aggregation_strategy == "constrained_linear_stacking":
        if bool(selection_settings.get("enabled", False)):
            raise ValueError(
                "constrained_linear_stacking retains all architectures; "
                "set selection.enabled=false."
            )
        linear_max_weight = float(
            weighting.get(
                "max_weight",
                float(weighting.get("max_weight_multiplier", 2.0)) / len(names),
            )
        )
        linear_min_effective = float(
            weighting.get(
                "min_effective_members",
                float(weighting.get("min_effective_fraction", 0.5)) * len(names),
            )
        )
        fit, _ = fit_constrained_linear_stacking(
            probability_matrix,
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            architecture_names=names,
            diversity_lambda=float(weighting.get("diversity_lambda", 0.02)),
            shrinkage_lambda=float(weighting.get("shrinkage_lambda", 0.10)),
            max_weight=linear_max_weight,
            min_effective_members=linear_min_effective,
            max_iterations=int(weighting.get("max_iterations", 5000)),
            tolerance=float(weighting.get("tolerance", 1e-10)),
            class_balance=bool(weighting.get("class_balance", True)),
        )
        architecture_weights[:] = np.asarray(fit.weights, dtype=np.float64)
        fold_values = np.unique(oof["fold"].to_numpy())
        cross_fitted_probability = np.empty(len(oof), dtype=np.float64)
        linear_oof_weight_matrix = np.empty_like(probability_matrix)
        linear_crossfit_weights = {}
        for held_out_fold in fold_values:
            train_mask = oof["fold"].to_numpy() != held_out_fold
            held_out_mask = ~train_mask
            fold_fit, _ = fit_constrained_linear_stacking(
                probability_matrix[train_mask],
                labels=oof.loc[train_mask, "label"].to_numpy(),
                patient_ids=oof.loc[train_mask, "patient_id"].astype(str).to_numpy(),
                architecture_names=names,
                diversity_lambda=float(weighting.get("diversity_lambda", 0.02)),
                shrinkage_lambda=float(weighting.get("shrinkage_lambda", 0.10)),
                max_weight=linear_max_weight,
                min_effective_members=linear_min_effective,
                max_iterations=int(weighting.get("max_iterations", 5000)),
                tolerance=float(weighting.get("tolerance", 1e-10)),
                class_balance=bool(weighting.get("class_balance", True)),
            )
            fold_weights = np.asarray(fold_fit.weights, dtype=np.float64)
            cross_fitted_probability[held_out_mask] = (
                probability_matrix[held_out_mask] @ fold_weights
            )
            linear_oof_weight_matrix[held_out_mask] = fold_weights
            linear_crossfit_weights[str(held_out_fold)] = fold_fit.as_dict()
        oof["spe_prob_1"] = cross_fitted_probability
        print(
            "Fitted constrained linear stacking: "
            f"effective_members={fit.effective_members:.3f}, "
            f"max_weight={max(fit.weights):.4f}"
        )
    elif aggregation_strategy == "ra_spe":
        if bool(selection_settings.get("enabled", False)):
            raise ValueError("ra_spe retains all architectures; set selection.enabled=false.")
        state_columns = [f"state_variance_{name}" for name in names]
        requested_state_variance = bool(aggregation.get("use_state_variance", True))
        oof_state_variances = None
        if requested_state_variance and set(state_columns).issubset(oof.columns):
            oof_state_variances = oof[state_columns].to_numpy(dtype=np.float64)
        elif requested_state_variance:
            print(
                "WARNING: cached OOF predictions have no per-architecture state "
                "variance; RA-SPE will use probability/entropy/disagreement features only."
            )
        ra_fit, ra_model, cross_fitted_probability, ra_oof_weights = fit_ra_spe(
            probability_matrix,
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            fold_ids=oof["fold"].to_numpy(),
            architecture_names=names,
            state_variances=oof_state_variances,
            hidden_dim=int(aggregation.get("hidden_dim", 16)),
            epochs=int(aggregation.get("epochs", 300)),
            learning_rate=float(aggregation.get("learning_rate", 0.002)),
            weight_decay=float(aggregation.get("weight_decay", 0.001)),
            member_dropout=float(aggregation.get("member_dropout", 0.20)),
            uniform_kl_lambda=float(aggregation.get("uniform_kl_lambda", 0.05)),
            consistency_lambda=float(aggregation.get("consistency_lambda", 0.10)),
            group_dro_temperature=float(
                aggregation.get("group_dro_temperature", 0.10)
            ),
            max_weight=float(
                aggregation.get(
                    "max_weight",
                    min(
                        1.0,
                        float(aggregation.get("max_weight_multiplier", 2.5))
                        / len(names),
                    ),
                )
            ),
            class_balance=bool(weighting.get("class_balance", True)),
            seed=int(aggregation.get("seed", 2026)),
        )
        # These are meta-level cross-fitted predictions, not predictions from
        # the final aggregator fitted on all OOF rows.
        oof["spe_prob_1"] = cross_fitted_probability
        architecture_weights[:] = ra_oof_weights.mean(axis=0)
        for index, name in enumerate(names):
            oof[f"ra_weight_{name}"] = ra_oof_weights[:, index]
        print(
            "Fitted RA-SPE: "
            f"cross-fitted BAcc={ra_fit.cross_fitted_balanced_accuracy:.6f}, "
            f"sensitivity={ra_fit.cross_fitted_sensitivity:.6f}, "
            f"specificity={ra_fit.cross_fitted_specificity:.6f}"
        )
    elif aggregation_strategy == "top1_anchor_fallback":
        if anchor_guard is None or anchor_guard_oof_probability is None:
            raise AssertionError("Top1-anchor guard was not fitted.")
        architecture_weights[:] = np.asarray(
            anchor_guard.deployed_weights, dtype=np.float64
        )
        oof["top1_anchor_prob_1"] = probability_matrix[
            :, names.index(anchor_guard.anchor_name)
        ]
        oof["proposed_anchor_ensemble_prob_1"] = (
            anchor_guard_proposed_oof_probability
        )
        oof["spe_prob_1"] = anchor_guard_oof_probability
    else:
        fit, _ = fit_architecture_weights(
            selected_probability_matrix,
            labels=oof["label"].to_numpy(),
            patient_ids=oof["patient_id"].astype(str).to_numpy(),
            architecture_names=selected_names,
            diversity_lambda=float(weighting.get("diversity_lambda", 0.05)),
            max_iterations=int(weighting.get("max_iterations", 5000)),
            tolerance=float(weighting.get("tolerance", 1e-10)),
            class_balance=bool(weighting.get("class_balance", False)),
        )
        architecture_weights[selected_indices] = np.asarray(
            fit.weights, dtype=np.float64
        )
        oof["spe_prob_1"] = probability_matrix @ architecture_weights
    oof["spe_prediction"] = (
        oof["spe_prob_1"] >= decision_threshold
    ).astype(int)
    if aggregation_strategy == "ra_spe":
        oof["architecture_disagreement"] = np.sqrt(
            np.sum(
                ra_oof_weights
                * (probability_matrix - oof["spe_prob_1"].to_numpy()[:, None]) ** 2,
                axis=1,
            )
        )
    elif linear_oof_weight_matrix is not None:
        oof["architecture_disagreement"] = np.sqrt(
            np.sum(
                linear_oof_weight_matrix
                * (probability_matrix - oof["spe_prob_1"].to_numpy()[:, None]) ** 2,
                axis=1,
            )
        )
    else:
        oof["architecture_disagreement"] = architecture_disagreement(
            probability_matrix, architecture_weights
        )
    atomic_csv(oof, output_root / "oof_architecture_predictions.csv")

    patient_ids = oof["patient_id"].astype(str).to_numpy()
    patient_weights = (
        class_patient_equal_sample_weights(oof["label"].to_numpy(), patient_ids)
        if bool(weighting.get("class_balance", False))
        else patient_equal_sample_weights(patient_ids)
    )
    similarity = residual_similarity_matrix(
        probability_matrix,
        oof["label"].to_numpy(),
        patient_weights,
    )
    similarity_frame = pd.DataFrame(similarity, index=names, columns=names)
    similarity_frame.index.name = "architecture"
    atomic_csv(similarity_frame.reset_index(), output_root / "residual_similarity.csv")

    weight_rows = []
    for index, name in enumerate(names):
        architecture_probability = probability_matrix[:, index]
        clipped = np.clip(architecture_probability, 1e-7, 1 - 1e-7)
        log_loss = -np.sum(
            patient_weights
            * (oof["label"] * np.log(clipped) + (1 - oof["label"]) * np.log(1 - clipped))
        )
        weight_rows.append(
            {
                "architecture": name,
                "selected": name in selected_names,
                "weight": architecture_weights[index],
                "proposed_weight": (
                    float(anchor_guard.proposed_weights[index])
                    if anchor_guard is not None
                    else architecture_weights[index]
                ),
                "ensemble_role": (
                    "anchor"
                    if anchor_guard is not None and name == anchor_guard.anchor_name
                    else (
                        "proposed_complement"
                        if anchor_guard is not None
                        and name in anchor_guard.proposed_selected_names
                        else "candidate"
                    )
                ),
                "weight_std": (
                    float(ra_oof_weights[:, index].std())
                    if ra_oof_weights is not None
                    else 0.0
                ),
                "weight_min": (
                    float(ra_oof_weights[:, index].min())
                    if ra_oof_weights is not None
                    else architecture_weights[index]
                ),
                "weight_max": (
                    float(ra_oof_weights[:, index].max())
                    if ra_oof_weights is not None
                    else architecture_weights[index]
                ),
                "patient_equal_oof_log_loss": float(log_loss),
                "mean_residual_similarity_to_others": float(
                    np.delete(similarity[index], index).mean()
                ),
            }
        )
    atomic_csv(pd.DataFrame(weight_rows), output_root / "architecture_weights.csv")

    test_probability_columns = [f"prob_{name}" for name in names]
    state_variance_columns = [f"state_variance_{name}" for name in names]
    fold_variance_columns = [f"fold_variance_{name}" for name in names]
    required_test_columns = (
        test_probability_columns + state_variance_columns + fold_variance_columns
    )
    missing_test_columns = set(required_test_columns).difference(test_base.columns)
    if missing_test_columns:
        raise ValueError(
            f"Test predictions are missing columns: {sorted(missing_test_columns)}"
        )
    atomic_csv(test_base, output_root / "architecture_test_predictions.csv")

    test_matrix = test_base[test_probability_columns].to_numpy(dtype=np.float64)
    state_variances = test_base[state_variance_columns].to_numpy(dtype=np.float64)
    fold_variances = test_base[fold_variance_columns].to_numpy(dtype=np.float64)
    final = test_base[["slide_id", "patient_id", "type", "label"]].copy()
    test_ra_weights = None
    if aggregation_strategy == "diversity_veto":
        final["prob_1"] = test_matrix[:, selected_indices].min(axis=1)
    elif aggregation_strategy == "sensitivity_constrained_subset":
        final["prob_1"] = test_matrix[:, selected_indices].mean(axis=1)
    elif aggregation_strategy == "ra_spe":
        if ra_model is None or ra_fit is None:
            raise AssertionError("RA-SPE model was not fitted.")
        test_ra_state_variances = state_variances if ra_fit.state_variance_used else None
        test_ra_probability, test_ra_weights = predict_ra_spe(
            ra_model, test_matrix, test_ra_state_variances
        )
        final["prob_1"] = test_ra_probability
        for index, name in enumerate(names):
            final[f"weight_{name}"] = test_ra_weights[:, index]
    else:
        final["prob_1"] = test_matrix @ architecture_weights
    if anchor_guard is not None:
        anchor_index = names.index(anchor_guard.anchor_name)
        final["top1_anchor_prob_1"] = test_matrix[:, anchor_index]
        final["proposed_anchor_ensemble_prob_1"] = test_matrix @ np.asarray(
            anchor_guard.proposed_weights, dtype=np.float64
        )
        final["automatic_fallback_applied"] = anchor_guard.fallback_triggered
        final["deployment_mode"] = (
            "top1_fallback"
            if anchor_guard.fallback_triggered
            else "top1_anchored_ensemble"
        )
    final["prob_0"] = 1.0 - final["prob_1"]
    final["prediction"] = (final["prob_1"] >= decision_threshold).astype(int)
    if test_ra_weights is not None:
        final["state_disagreement"] = np.sqrt(
            np.sum(state_variances * test_ra_weights, axis=1)
        )
        final["fold_disagreement"] = np.sqrt(
            np.sum(fold_variances * test_ra_weights, axis=1)
        )
        final["architecture_disagreement"] = np.sqrt(
            np.sum(
                test_ra_weights
                * (test_matrix - final["prob_1"].to_numpy()[:, None]) ** 2,
                axis=1,
            )
        )
    else:
        final["state_disagreement"] = np.sqrt(state_variances @ architecture_weights)
        final["fold_disagreement"] = np.sqrt(fold_variances @ architecture_weights)
        final["architecture_disagreement"] = architecture_disagreement(
            test_matrix, architecture_weights
        )
    final["equal_weight_prob_1"] = test_matrix.mean(axis=1)
    final["equal_weight_prediction"] = (
        final["equal_weight_prob_1"] >= threshold
    ).astype(int)
    final["majority_vote_prediction"] = (
        (test_matrix >= threshold).sum(axis=1) >= (len(names) // 2 + 1)
    ).astype(int)
    atomic_csv(final, output_root / "spe_predictions.csv")
    if ra_model is not None and ra_fit is not None:
        checkpoint_path = output_root / "ra_spe_aggregator.pt"
        temporary_checkpoint = checkpoint_path.with_suffix(".pt.tmp")
        torch.save(ra_spe_checkpoint(ra_fit, ra_model), temporary_checkpoint)
        temporary_checkpoint.replace(checkpoint_path)

    config_hash = hashlib.sha256(config_path.read_bytes()).hexdigest()
    manifest = {
        "schema_version": 2 if aggregation_strategy == "top1_anchor_fallback" else 1,
        "method": (
            "best-state-top1-anchor-automatic-fallback"
            if aggregation_strategy == "top1_anchor_fallback"
            else "stability-prioritized-hierarchical-ensemble"
        ),
        "paper_hierarchy": (
            None
            if aggregation_strategy == "top1_anchor_fallback"
            else [
                "stable_checkpoint_states",
                "five_folds",
                "development_selected_architectures",
            ]
        ),
        "design_story": (
            [
                "one_best_state_per_fold",
                "development_oof_top1_anchor",
                "bounded_complement_risk_budget",
                "oof_gain_and_fold_stability_guardrail",
                "automatic_top1_fallback",
            ]
            if aggregation_strategy == "top1_anchor_fallback"
            else None
        ),
        "spe_config": str(config_path),
        "spe_config_sha256": config_hash,
        "experiment_name": experiment_name,
        "cohort": cohort_name,
        "test_dataset_override": (
            None
            if cli.test_dataset_csv is None
            else str(resolve_path(cli.test_dataset_csv))
        ),
        "development_only_weight_fit": aggregation_strategy in {
            "weighted_mean",
            "constrained_linear_stacking",
            "ra_spe",
            "top1_anchor_fallback",
        },
        "independent_test_labels_used_for_fit": False,
        "refit_from": None if refit_source is None else str(refit_source),
        "configured_classification_threshold": threshold,
        "classification_threshold": decision_threshold,
        "checkpoint_selection": checkpoint_selection,
        "inference_devices": devices,
        "aggregation": {
            "strategy": aggregation_strategy,
            "selected_names": selected_names,
            "classification_threshold": decision_threshold,
            "reference_selection": (
                None if reference_selection is None else reference_selection.as_dict()
            ),
            "reference_weight_fit": (
                None if reference_fit is None else reference_fit.as_dict()
            ),
            "ra_spe_fit": None if ra_fit is None else ra_fit.as_dict(),
            "linear_crossfit_weights": linear_crossfit_weights,
            "top1_anchor_guard": (
                None if anchor_guard is None else anchor_guard.as_dict()
            ),
        },
        "architecture_selection": (
            selection.as_dict()
            if selection is not None
            else {
                "enabled": False,
                "selected_names": names,
            }
        ),
        "weight_fit": None if fit is None else fit.as_dict(),
        "architectures": run_manifest,
        "outputs": {
            "oof": str(output_root / "oof_architecture_predictions.csv"),
            "weights": str(output_root / "architecture_weights.csv"),
            "residual_similarity": str(output_root / "residual_similarity.csv"),
            "architecture_test": str(output_root / "architecture_test_predictions.csv"),
            "spe_predictions": str(output_root / "spe_predictions.csv"),
            "ra_spe_checkpoint": (
                None
                if ra_model is None
                else str(output_root / "ra_spe_aggregator.pt")
            ),
        },
    }
    atomic_json(manifest, output_root / "manifest.json")
    print(f"SPE complete: {output_root / 'spe_predictions.csv'}")


if __name__ == "__main__":
    main()
